[tool.poetry]
name = "eoq-3"
version = "0.1.0"
description = ""
authors = ["Hugo <551108@student.saxion.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.1.0"
pygame = "^2.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
